### ISSUE TITLE
orange oct issues

### ISSUE THREAD

**Issue by Stavinair** [theangelurd/Additional-Content#1]
Removed a unneeded } that gave one error for orange oct, but unfortunately another showed up. Running latest mindustry on android 6.0
![Screenshot_2021-01-06-09-18-03](https://user-images.githubusercontent.com/57328437/103785176-8403dd80-5000-11eb-95b0-dfbbb0e675dd.png)

**Comment by LostCause122** [comment]
Unneeded  } in orange oct files

**Comment by theangelurd** [comment]
i'll fix that now, i'm gonna add a bullet to the orange oct, it's just that i had to pause it because of the time being late
